src/SubtitlesManagementSystem.Web/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using Data.DataModels.Entities;
using Microsoft.AspNetCore.Authorization;
using SubtitlesManagementSystem.Business.Services.Actors;
using SubtitlesManagementSystem.Business.Transactions.Interfaces;
using SubtitlesManagementSystem.Common.GlobalConstants;
using SubtitlesManagementSystem.Web.Models.Actors.BindingModels;
using SubtitlesManagementSystem.Web.Models.Actors.ViewModels;
using System.Data;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using SubtitlesManagementSystem.Common.Helpers;

namespace SubtitlesManagementSystem.Web.Controllers
{
    public class ActorsController : BaseController
    {
        private readonly IActorService _actorService;

        private readonly IUnitOfWork _unitOfWork;

        public ActorsController(IActorService actorService, IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _actorService = actorService;
        }

        [Authorize(Roles = "Administrator, Editor")]
        public IActionResult Index(string sortOrder, string currentFilter, string searchTerm, int? pageSize, int? pageNumber)
        {
            IEnumerable<AllActorsViewModel> allActorsViewModel = _actorService.GetAllActors();

            ViewData["CurrentSort"] = sortOrder;
            ViewData["ActorFirstNameSort"] = string.IsNullOrEmpty(sortOrder)
                ? "actor_first_name_descending"
                : "";
            ViewData["ActorLastNameSort"] = sortOrder == "actor_last_name_ascending"
                ? "actor_last_name_descending"
                : "actor_last_name_ascending";

            if (searchTerm != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchTerm = currentFilter;
            }

            ViewData["ActorSearchFilter"] = searchTerm;

            if (!string.IsNullOrEmpty(searchTerm))
            {
                allActorsViewModel = allActorsViewModel
                        .Where(aavm =>
                            aavm.FirstName.ToLower().Contains(searchTerm.ToLower()) ||
                            aavm.LastName.ToLower().Contains(searchTerm.ToLower())
                        );
            }

            allActorsViewModel = sortOrder switch
            {
                "actor_first_name_descending" => allActorsViewModel
                        .OrderByDescending(aavm => aavm.FirstName),
                "actor_last_name_ascending" => allActorsViewModel
                        .OrderBy(aavm => aavm.LastName),
                "actor_last_name_descending" => allActorsViewModel
                        .OrderByDescending(aavm => aavm.LastName),
                _ => allActorsViewModel.OrderBy(aavm => aavm.FirstName)
            };

            pageSize ??= 3;

            ViewData["CurrentPageSize"] = pageSize;

            var actorsPaginatedList = PaginatedList<AllActorsViewModel>
                .Create(allActorsViewModel, pageNumber ?? 1, (int)pageSize);

            return View(actorsPaginatedList);
        }

        [Authorize(Roles = "Administrator, Editor")]
        public IActionResult Details(string id)
        {
            ActorDetailsViewModel actorDetailsViewModel = _actorService.GetActorDetails(id);

            if (actorDetailsViewModel == null)
            {
                return NotFound();
            }

            return View(actorDetailsViewModel);
        }

        [Authorize(Roles = "Administrator, Editor")]
        public ViewResult Create()
        {
            return View(_actorService.GetActorCreatingDetails());
        }

        [HttpPost]
        [Authorize(Roles = "Administrator, Editor")]
        //[ValidateAntiForgeryToken]
        public IActionResult Create(
            CreateActorBindingModel createActorBindingModel,
            string[] selectedFilmProductions
         )
        {
            if (!ModelState.IsValid)
            {
                return View(createActorBindingModel);
            }

            bool isNewActorCreated = _actorService.CreateActor(
                createActorBindingModel, selectedFilmProductions, User.FindFirstValue(ClaimTypes.Name)
            );

            if (!isNewActorCreated)
            {
                TempData["ActorErrorMessage"] = string.Format(
                        NotificationMessages.ExistingRecordErrorMessage,
                        "actor", $"{createActorBindingModel.FirstName} " +
                        $"{createActorBindingModel.LastName}"
                    );

                return View(createActorBindingModel);
            }

            bool isNewActorSavedToDatabase = _unitOfWork.CommitSaveChanges();

            if (!isNewActorSavedToDatabase)
            {
                TempData["ActorErrorMessage"] = string.Format(
                    NotificationMessages.NewRecordFailedSaveErrorMessage, "actor"
                );

                return View(createActorBindingModel);
            }

            TempData["ActorSuccessMessage"] = string.Format(
                    NotificationMessages.RecordCreationSuccessMessage,
                    "Actor", $"{createActorBindingModel.FirstName} " +
                    $"{createActorBindingModel.LastName}"
                );

            return RedirectToIndexActionInCurrentController();
        }

        [Authorize(Roles = "Administrator, Editor")]
        public IActionResult Edit(string id)
        {
            EditActorBindingModel editActorBindingModel = _actorService
                .GetActorEditingDetails(id);

            if (editActorBindingModel == null)
            {
                return NotFound();
            }

            return View(editActorBindingModel);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator, Editor")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(
            EditActorBindingModel editActorBindingModel,
            string[] selectedFilmProductions
        )
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return View(editActorBindingModel);
            }

            bool isCurrentActorEdited = _actorService.EditActor(
                editActorBindingModel, selectedFilmProductions, User.FindFirstValue(ClaimTypes.Name)
            );

            if (!isCurrentActorEdited)
            {
                TempData["ActorErrorMessage"] = string.Format(
                        NotificationMessages.ExistingRecordErrorMessage,
                        "actor", $"{editActorBindingModel.FirstName} " +
                        $"{editActorBindingModel.LastName}"
                    );

                return View(editActorBindingModel);
            }

            bool isCurrentActorUpdateSavedToDatabase = _unitOfWork.CommitSaveChanges();

            if (!isCurrentActorUpdateSavedToDatabase)
            {
                TempData["ActorErrorMessage"] = string.Format(
                    NotificationMessages.RecordFailedUpdateSaveErrorMessage,
                    "actor"
                  );

                return View(editActorBindingModel);
            }

            TempData["ActorSuccessMessage"] = string.Format(
                   NotificationMessages.RecordUpdateSuccessMessage,
                   "Actor", $"{editActorBindingModel.FirstName} " +
                   $"{editActorBindingModel.LastName}"
                );

            return RedirectToIndexActionInCurrentController();
        }

        [Authorize(Roles = IdentityConstants.AdministratorRoleName)]
        public IActionResult Delete(string id)
        {
            DeleteActorViewModel deleteActorViewModel = _actorService
                .GetActorDeletionDetails(id);

            if (deleteActorViewModel == null)
            {
                return NotFound();
            }

            return View(deleteActorViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = IdentityConstants.AdministratorRoleName)]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmDeletion(string id)
        {
            Actor actorToConfirmDeletion = _actorService.FindActor(id);

            _actorService.DeleteActor(actorToConfirmDeletion);

            bool isActorDeleted = _unitOfWork.CommitSaveChanges();

            if (!isActorDeleted)
            {
                TempData["ActorErrorMessage"] = string.Format(
                    NotificationMessages.RecordFailedDeletionErrorMessage,
                    "actor"
                   ) + $" {actorToConfirmDeletion.FirstName} " +
                   $"{actorToConfirmDeletion.LastName}";

                return RedirectToAction(nameof(Delete));
            }

            TempData["ActorSuccessMessage"] = string.Format(
                    NotificationMessages.RecordDeletionSuccessMessage,
                    "Actor", $"{actorToConfirmDeletion.FirstName} " +
                    $"{actorToConfirmDeletion.LastName}"
                  );

            return RedirectToIndexActionInCurrentController();
        }
    }
}

src/SubtitlesManagementSystem.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using SubtitlesManagementSystem.Business.Services.Users;
using SubtitlesManagementSystem.Business.Transactions.Interfaces;
using SubtitlesManagementSystem.Common.GlobalConstants;
using SubtitlesManagementSystem.Common.Helpers;
using SubtitlesManagementSystem.Web.Models.Users;
using System.Security.Claims;

namespace SubtitlesManagementSystem.Web.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersController : BaseController
    {
        private readonly IUserService _userService;

        private readonly IUnitOfWork _unitOfWork;

        public UsersController(IUserService userService, IUnitOfWork unitOfWork)
        {
            _userService = userService;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index(string sortOrder, string currentFilter, string searchTerm, int? pageSize, int? pageNumber)
        {
            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            IEnumerable<AllUsersViewModel> allUsersViewModel = _userService.GetAllUsers(currentUserId);

            bool isAlUsersViewModelEmpty = allUsersViewModel.Count() == 0;

            if (isAlUsersViewModelEmpty)
            {
                return NotFound();
            }

            ViewData["CurrentSort"] = sortOrder;
            ViewData["UserNameSort"] = string.IsNullOrEmpty(sortOrder)
                ? "user_name_descending"
                : "";

            if (searchTerm != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchTerm = currentFilter;
            }

            ViewData["UserSearchFilter"] = searchTerm;

            if (!string.IsNullOrEmpty(searchTerm))
            {
                allUsersViewModel = allUsersViewModel
                        .Where(acvm =>
                            acvm.Username.ToLower().Contains(searchTerm.ToLower())
                        );
            }

            allUsersViewModel = sortOrder switch
            {
                "user_name_descending" => allUsersViewModel
                        .OrderByDescending(acvm => acvm.Username),
                _ => allUsersViewModel.OrderBy(acvm => acvm.Username)
            };

            pageSize ??= 3;

            ViewData["CurrentPageSize"] = pageSize;

            var usersPaginatedList = PaginatedList<AllUsersViewModel>
                .Create(allUsersViewModel, pageNumber ?? 1, (int)pageSize);

            return View(usersPaginatedList);
        }

        public async Task<IActionResult> Promote(string id)
        {
            await _userService.PromoteUser(id);
            _unitOfWork.CommitSaveChanges();

            return RedirectToIndexActionInCurrentController();
        }

        public IActionResult DeclinePromotion(string id)
        {
            _userService.DeclinePromotion(id);
            _unitOfWork.CommitSaveChanges();

            return RedirectToIndexActionInCurrentController();
        }

        public async Task<IActionResult> Demote(string id)
        {
            await _userService.DemoteUser(id);
            _unitOfWork.CommitSaveChanges();

            return RedirectToIndexActionInCurrentController();
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(string id)
        {
            DeleteUserViewModel deleteUserViewModel = _userService.GetUserDeletionDetails(id);

            if (deleteUserViewModel == null)
            {
                return NotFound();
            }

            if (User.FindFirstValue(ClaimTypes.NameIdentifier) == deleteUserViewModel.Id)
            {
                TempData["UserInvalidOperationErrorMessage"] = "Error! The admin cannot delete himself!";

                return RedirectToIndexActionInCurrentController();
            }

            return View(deleteUserViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var userToConfirmDeletion = _userService.FindUser(id);

            bool isUserDeleted = await _userService.DeleteUser(userToConfirmDeletion.Id);

            if (isUserDeleted)
            {
                _unitOfWork.CommitSaveChanges();
            }
            else
            {
                string userFailedDeletionErrorMessage = NotificationMessages
                    .RecordFailedDeletionErrorMessage;

                TempData["UserErrorMessage"] =
                    string.Format(userFailedDeletionErrorMessage, "user") +
                    $" {userToConfirmDeletion.UserName}!";

                return RedirectToAction(nameof(Delete));
            }

            TempData["UserSuccessMessage"] = string.Format(
                NotificationMessages.RecordDeletionSuccessMessage,
                "User", $"{userToConfirmDeletion.UserName}"
            );

            return RedirectToIndexActionInCurrentController();
        }
    }
}

src/SubtitlesManagementSystem.Web/Views/Shared/_Footer.cshtml
<div class="footer" style="background-color: #a12c2f; margin-top: 0;">
    <p style="color: white;">
        Copyright © 2023 Subsogator, Ltd. All Rights Reserved.
        Distibuted By: Subtitles Management System
    </p>
</div>

src/SubtitlesManagementSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SubtitlesManagementSystem.Web</title>
    @*     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SubtitlesManagementSystem.Web.styles.css" asp-append-version="true" />

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-edu-meeting.css">
    <link rel="stylesheet" href="~/assets/css/owl.css">
    <link rel="stylesheet" href="~/assets/css/lightbox.css">
</head>
<body>
    @{
        var currentRequestPath = @Context.Request.Path;
    }

    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky @(currentRequestPath != "/SubtitlesCatalogue" ? "background-header" : "")">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Menu Start ***** -->
                        <a asp-controller="Home" asp-action="Index" class="logo">
                            Subsogator
                        </a>
                        <ul class="nav">
                            <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li><a asp-area="" asp-controller="Favourites" asp-action="Index">Favourites</a></li>
                            }
                            @if (User.IsInRole(AdministratorRoleName) || User.IsInRole(EditorRoleName) || User.IsInRole(UploaderRoleName))
                            {
                                <li class="has-sub">
                                    <a href="javascript:void(0)">Dashboard</a>
                                    <ul class="sub-menu">
                                        @if (User.IsInRole(AdministratorRoleName) || User.IsInRole(EditorRoleName))
                                        {
                                            <li>
                                                <a asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                                            </li>
                                            <li>
                                                <a asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
                                            </li>
                                            <li>
                                                <a asp-area="" asp-controller="Languages" asp-action="Index">Languages</a>
                                            </li>
                                            <li>
                                                <a asp-area="" asp-controller="Actors" asp-action="Index">Actors</a>
                                            </li>
                                            <li>
                                                <a asp-area="" asp-controller="Directors" asp-action="Index">Directors</a>
                                            </li>
                                            <li>
                                                <a asp-area="" asp-controller="Screenwriters" asp-action="Index">Screenwriters</a>
                                            </li>
                                            <li>
                                                <a asp-area="" asp-controller="FilmProductions" asp-action="Index">Film Productions</a>
                                            </li>
                                            @if (User.IsInRole(AdministratorRoleName))
                                            {
                                                <li>
                                                    <a asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                                </li>
                                            }
                                        }
                                        <li>
                                            <a asp-area="" asp-controller="Subtitles" asp-action="Index">Subtitles</a>
                                        </li>
                                    </ul>
                                </li>
                            }
                            @if (User.IsInRole(NormalUserRole))
                            {
                                <li>
                                    <a asp-controller="Home" asp-action="BecomeAnUploader">Become An Uploader</a>
                                </li>
                            }
                            @if (User.IsInRole(UploaderRoleName))
                            {
                                <li>
                                    <a asp-controller="Home" asp-action="BecomeAnEditor">Become An Editor</a>
                                </li>
                            }
                            <partial name="_LoginPartial" />
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <!-- ***** Header Area End ***** -->

    @if (@currentRequestPath == "/SubtitlesCatalogue")
    {
        <!-- ***** Main Banner Area Start ***** -->
        <section class="section main-banner" id="top" data-section="section1">
            <video autoplay muted loop id="bg-video">
                <source src="assets/images/DUNE_ PART TWO – Final Trailer (2024) Timothée Chalamet, Zendaya Movie _ Warner Bros (online-video-cutter.com).mp4" type="video/mp4" />
            </video>

            <div class="video-overlay header-text">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="caption">
                                <h6>Hello Movies Fans</h6>
                                <h2>Welcome to Subsogator</h2>
                                <p>
                                    This is a scalable subtitles management system platform, which enables the user to upload subtitles after approval.
                                    However, non-registered users can also download the archives of the multiple subtitles, which can be viewed.
                                </p>
                                <div class="main-button-red">
                                    <div class="scroll-to-section"><a href="#contact">Download Now</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- ***** Main Banner Area End ***** -->
    }

    @RenderBody()

    <partial name="_Footer" />

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/assets/js/isotope.min.js"></script>
    <script src="~/assets/js/owl-carousel.js"></script>
    <script src="~/assets/js/lightbox.js"></script>
    <script src="~/assets/js/tabs.js"></script>
    <script src="~/assets/js/video.js"></script>
    <script src="~/assets/js/slick-slider.js"></script>
    <script src="~/assets/js/custom.js"></script>
    <script>
        $('.nav li:first').addClass('active');

        var showSection = function showSection(section, isAnimate) {
            var
                direction = section.replace(/#/, ''),
                reqSection = $('.section').filter('[data-section="' + direction + '"]'),
                reqSectionPos = reqSection.offset().top - 0;

            if (isAnimate) {
                $('body, html').animate({
                    scrollTop: reqSectionPos
                },
                    800);
            } else {
                $('body, html').scrollTop(reqSectionPos);
            }

        };

        var checkSection = function checkSection() {
            $('.section').each(function () {
                var
                    $this = $(this),
                    topEdge = $this.offset().top - 80,
                    bottomEdge = topEdge + $this.height(),
                    wScroll = $(window).scrollTop();
                if (topEdge < wScroll && bottomEdge > wScroll) {
                    var
                        currentId = $this.data('section'),
                        reqLink = $('a').filter('[href*=\\#' + currentId + ']');
                    reqLink.closest('li').addClass('active').
                        siblings().removeClass('active');
                }
            });
        };

        $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {
            e.preventDefault();
            showSection($(this).attr('href'), true);
        });

        $(window).scroll(function () {
            checkSection();
        });
    </script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>