src/SubtitlesManagementSystem.Web/Controllers/SubtitlesCatalogueController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SubtitlesManagementSystem.Business.Services.Comments;
using SubtitlesManagementSystem.Business.Services.Favourites;
using SubtitlesManagementSystem.Business.Services.Subtitles;
using SubtitlesManagementSystem.Business.Services.SubtitlesCatalogue;
using SubtitlesManagementSystem.Business.Transactions.Interfaces;
using SubtitlesManagementSystem.Common.Helpers;
using SubtitlesManagementSystem.Web.Models.Comments.BindingModels;
using SubtitlesManagementSystem.Web.Models.SubtitlesCatalogue;
using System.IO.Compression;
using System.Security.Claims;

namespace SubtitlesManagementSystem.Web.Controllers
{
    [AllowAnonymous]
    public class SubtitlesCatalogueController : BaseController
    {
        private readonly ISubtitlesCatalogueService _subtitlesCatalogueService;

        private readonly ISubtitlesService _subtitlesService;

        private readonly ICommentService _commentService;

        private readonly IFavouritesService _favouritesService;

        private readonly IUnitOfWork _unitOfWork;

        private IWebHostEnvironment _webHostEnvironment;

        private ILogger _logger;

        public SubtitlesCatalogueController(
            ISubtitlesCatalogueService subtitlesCatalogueService,
            ISubtitlesService subtitlesService,
            ICommentService commentService,
            IFavouritesService favouritesService,
            IUnitOfWork unitOfWork,
            IWebHostEnvironment webHostEnvironment,
            ILogger<SubtitlesCatalogueController> logger
        )
        {
            _subtitlesCatalogueService = subtitlesCatalogueService;
            _subtitlesService = subtitlesService;
            _commentService = commentService;
            _favouritesService = favouritesService;
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }

        public IActionResult Index(string currentFilter, string searchTerm, int? pageSize, int? pageNumber)
        {
            var catalogueItemsViewModel = _subtitlesCatalogueService.GetAllSubtitlesForCatalogue();

            bool isAllSubtitlesForCatalogueViewModelEmpty = catalogueItemsViewModel.AllSubtitlesForCatalogue.Count() == 0;

            if (isAllSubtitlesForCatalogueViewModelEmpty)
            {
                return NotFound();
            }

            if (searchTerm != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchTerm = currentFilter;
            }

            ViewData["SubtitlesCatalogueSearchFilter"] = searchTerm;

            if (!string.IsNullOrEmpty(searchTerm))
            {
                catalogueItemsViewModel.AllSubtitlesForCatalogue = catalogueItemsViewModel.AllSubtitlesForCatalogue
                        .Where(ascvm =>
                            ascvm.Name.ToLower().Contains(searchTerm.ToLower()) ||
                            ascvm.RelatedFilmProduction.ReleaseDate.Year.ToString().ToLower()
                                                .Contains(searchTerm.ToLower()) ||
                            ascvm.RelatedFilmProduction.CountryName.ToLower()
                                                .Contains(searchTerm.ToLower()) ||
                            ascvm.RelatedFilmProduction.LanguageName.ToLower()
                                                .Contains(searchTerm.ToLower())
                        );
            }

            pageSize ??= 5;

            ViewData["CurrentPageSize"] = pageSize;

            var subtitlesCataloguePaginatedList = PaginatedList<AllSubtitlesForCatalogueViewModel>
                .Create(catalogueItemsViewModel.AllSubtitlesForCatalogue, pageNumber ?? 1, (int)pageSize);

            CatalogueItemsWithPaginationViewModel catalogueItemsWithPaginationViewModel = new CatalogueItemsWithPaginationViewModel
            {
                AllSubtitlesForCatalogue = subtitlesCataloguePaginatedList,
                LatestComments = catalogueItemsViewModel.LatestComments,
                TopSubtitles = catalogueItemsViewModel.TopSubtitles
            };

            return View(catalogueItemsWithPaginationViewModel);
        }

        public IActionResult Details(string id)
        {
            SubtitlesCatalogueItemDetailsViewModel subtitlesDetailsViewModel = _subtitlesCatalogueService
                .GetSubtitlesCatalogueItemDetails(id);

            if (subtitlesDetailsViewModel == null)
            {
                return NotFound();
            }

            var correspondingComments = _commentService
                    .GetAllCommentsForSubtitlesCatalogueItem(id)
                        .OrderByDescending(c => c.CreatedOn)
                            .ToList();

            subtitlesDetailsViewModel.Comments = correspondingComments;

            return View(subtitlesDetailsViewModel);
        }

        public IActionResult AddToFavourites(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var subtitlesFavouritesReference = _subtitlesService.FindSubtitles(id);

            bool isSubtitlesAddedToFavourites = _favouritesService.AddToFavourites(userId, id);

            if (!isSubtitlesAddedToFavourites)
            {
                TempData["SubtitlesCatalogueInfoMessage"] = $"{subtitlesFavouritesReference.Name} is already in favourites list!";

                return RedirectToAction(nameof(Details), new { id });
            }

            bool isNewUserFavouritesSavedToDatabase = _unitOfWork.CommitSaveChanges();

            if (!isNewUserFavouritesSavedToDatabase)
            {
                TempData["SubtitlesCatalogueInfoMessage"] = "Couldn't save favourites to database!";

                return RedirectToAction(nameof(Details), new { id });
            }

            TempData["SubtitlesCatalogueInfoMessage"] = $"Sucessfully added {subtitlesFavouritesReference.Name} to favourites!";

            return RedirectToAction(nameof(Details), new { id });
        }

        public async Task<IActionResult> DownloadSubtitles(string id)
        {
            var subtitles = _subtitlesService.GetAllToList()
                    .Where(s => s.Id == id)
                        .FirstOrDefault();

            string wwwRootPath = _webHostEnvironment.WebRootPath;

            string subtitlesDirectoryOutputPath =
                Path.Combine(wwwRootPath + @$"\archives\subtitles\{subtitles.FilmProductionId}");

            if (!Directory.Exists(subtitlesDirectoryOutputPath))
            {
                TempData["SubtitlesCatalogueInfoMessage"] =
                   "An archive for this subtitles cannot be downloaded due to lack of uploaded files";

                return RedirectToAction(nameof(Details), new { subtitles.Id });
            }
            else
            {
                var subtitlesFilePaths = Directory.GetFiles(subtitlesDirectoryOutputPath);

                var zipFileMemoryStream = new MemoryStream();

                using (ZipArchive zipArchive = new ZipArchive(
                        zipFileMemoryStream, ZipArchiveMode.Update, leaveOpen: true
                ))
                {
                    foreach (var subtitlesFilePath in subtitlesFilePaths)
                    {
                        var subtitlesFileName = Path.GetFileName(subtitlesFilePath);
                        var entry = zipArchive.CreateEntry(subtitlesFileName);

                        using (var entryStream = entry.Open())
                        using (var fileStream = System.IO.File.OpenRead(subtitlesFilePath))
                        {
                            await fileStream.CopyToAsync(entryStream);
                        }
                    }
                }

                zipFileMemoryStream.Seek(0, SeekOrigin.Begin);

                return File(zipFileMemoryStream, "application/zip", $"{subtitles.Name}.zip");
            }
        }

        public IActionResult WriteComment(
            SubtitlesCatalogueItemDetailsViewModel subtitlesCatalogueDetailsViewModel
        )
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var createCommentBindingModel = new CreateCommentBindingModel
            {
                Content = subtitlesCatalogueDetailsViewModel.CommentContent
            };

            bool isNewCommentCreated = _commentService
                .CreateComment(createCommentBindingModel, subtitlesCatalogueDetailsViewModel.Id, userId);

            if (!isNewCommentCreated)
            {
                TempData["SubtitlesCatalogueInfoMessage"] = "Couldn't create comment!";

                return RedirectToAction(nameof(Details), new { subtitlesCatalogueDetailsViewModel.Id });
            }

            bool isNewCommentSavedToDatabase = _unitOfWork.CommitSaveChanges();

            if (!isNewCommentSavedToDatabase)
            {
                TempData["SubtitlesCatalogueInfoMessage"] = "Couldn't save comment to database!";

                return RedirectToAction(nameof(Details), new { subtitlesCatalogueDetailsViewModel.Id });
            }

            TempData["SubtitlesCatalogueInfoMessage"] = "Comment added successfully!";

            return RedirectToAction(nameof(Details), new { subtitlesCatalogueDetailsViewModel.Id });
        }
    }
}

src/SubtitlesManagementSystem.Web/Views/SubtitlesCatalogue/Details.cshtml
@using System.Globalization
@model SubtitlesManagementSystem.Web.Models.SubtitlesCatalogue.SubtitlesCatalogueItemDetailsViewModel

<section class="meetings-page" id="meetings">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="meeting-single-item">
                            <div class="thumb">
                                @if (Model.CreatedOn != default)
                                {
                                    @if (Model.ModifiedOn != null)
                                    {
                                        <div class="date">
                                            @{
                                                var subtitlesUploadedOnAbbreviatedMonthName = CultureInfo.CurrentCulture.DateTimeFormat.GetAbbreviatedMonthName(Model.ModifiedOn.Value.Month);
                                            }
                                            <h6>
                                                @Html.DisplayFor(subtitlesModelItem => subtitlesUploadedOnAbbreviatedMonthName)
                                                <span>@Html.DisplayFor(model => model.ModifiedOn!.Value.Day)</span>
                                            </h6>
                                        </div>
                                    }
                                }
                                <a asp-action="Details" asp-route-id="@Model.Id">
                                    @if (Model.RelatedFilmProduction.ImageName != null)
                                    {
                                        <img src="~/images/film-productions/@Model.RelatedFilmProduction.ImageName"
                                             class="rounded-square"
                                             asp-append-version="true" style="width: 100%; height: 600px;" />
                                        <br />
                                    }
                                    else
                                    {
                                        <img src="~/images/film-productions/istockphoto-1147544807-612x612.jpg" style="width: 100%; height: 600px;" />
                                    }
                                </a>
                            </div>
                            <div class="down-content" style="border: 1px solid">
                                <h2 class="text-danger">Film Production: @Html.DisplayFor(model => model.RelatedFilmProduction.Title)</h2>
                                <dl class="row bg-secondary mt-3">
                                    <dt class="col-sm-3 text-white bg-danger" style="font-weight: 400">
                                        @Html.DisplayNameFor(model => model.CreatedOn)
                                    </dt>
                                    <dd class="col-sm-9 text-white font-weight-normal">
                                        @Html.DisplayFor(model => model.CreatedOn)
                                    </dd>
                                    <dt class="col-sm-3 text-white bg-danger" style="font-weight: 400">
                                        Uploaded By
                                    </dt>
                                    <dd class="col-sm-9 text-white font-weight-normal">
                                        @Html.DisplayFor(model => model.UploaderUserName)
                                    </dd>
                                    <dt class="col-sm-3 text-white bg-danger" style="font-weight: 400">
                                        Release Date
                                    </dt>
                                    <dd class="col-sm-9 text-white font-weight-normal">
                                        @Model.RelatedFilmProduction.ReleaseDate.ToShortDateString()
                                    </dd>
                                    <dt class="col-sm-3 text-white bg-danger" style="font-weight: 400">
                                        Duration
                                    </dt>
                                    <dd class="col-sm-9 text-white font-weight-normal">
                                        @Html.DisplayFor(model => model.RelatedFilmProduction.Duration)
                                    </dd>
                                    <dt class="col-sm-3 text-white bg-danger" style="font-weight: 400">
                                        Country
                                    </dt>
                                    <dd class="col-sm-9 text-white font-weight-normal">
                                        @Html.DisplayFor(model => model.RelatedFilmProduction.CountryName)
                                    </dd>
                                    <dt class="col-sm-3 text-white bg-danger" style="font-weight: 400">
                                        Language
                                    </dt>
                                    <dd class="col-sm-9 text-white font-weight-normal">
                                        @Html.DisplayFor(model => model.RelatedFilmProduction.LanguageName)
                                    </dd>
                                    <dt class="col-sm-3 text-white bg-danger" style="font-weight: 400">
                                        @Html.DisplayNameFor(model => model.ModifiedOn)
                                    </dt>
                                    <dd class="col-sm-9 text-white font-weight-normal">
                                        @Html.DisplayFor(model => model.ModifiedOn)
                                    </dd>
                                </dl>
                                <h3 class="mt-3">@Html.DisplayFor(model => model.Name)</h3>
                                <p class="text-center">
                                    <a class="btn btn-primary" asp-controller="SubtitlesCatalogue" asp-action="DownloadSubtitles" asp-route-id="@Model.Id">Download</a>
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <a class="btn btn-dark" asp-controller="SubtitlesCatalogue" asp-action="AddToFavourites" asp-route-id="@Model.Id">Add To Favourites</a>
                                    }
                                </p>
                                <div class="row d-block w-100">
                                    <div class="mt-5">
                                        @foreach (var comment in Model.Comments)
                                        {
                                            @if (comment.Content != null)
                                            {
                                                <span class="badge bg-primary">By @comment.Username</span>
                                                <span class="bg-secondary">@comment.CreatedOn</span>
                                                <div class="alert alert-info" role="alert">
                                                    @comment.Content
                                                </div>
                                            }
                                        }
                                    </div>
                                </div>

                                @if (User.Identity.IsAuthenticated)
                                {
                                    <div class="row d-block w-100">
                                        <form asp-action="WriteComment" class="mt-5">
                                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                            <div>
                                                <input type="hidden" asp-for="Id" />
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">Comment</label>
                                                <textarea asp-for="CommentContent" class="form-control" style="width: 100%;"></textarea>
                                                <span asp-validation-for="CommentContent" class="text-danger"></span>
                                            </div>
                                            <div class="form-group mt-5">
                                                <input type="submit" value="Write Comment" class="btn btn-primary" />
                                            </div>
                                            @if (TempData["SubtitlesCatalogueInfoMessage"] != null)
                                            {
                                                <div class="alert alert-info" role="alert">
                                                    @TempData["SubtitlesCatalogueInfoMessage"]
                                                </div>
                                            }
                                        </form>
                                    </div>
                                }
                                else
                                {
                                    <div class="alert alert-danger" role="alert">
                                        <p>You must register / log in, in order to write comments</p>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="main-button-red mb-5">
                            <a asp-controller="Home" asp-action="Index">Back To Subtitles Catalogue</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

src/SubtitlesManagementSystem.Web/Views/SubtitlesCatalogue/Index.cshtml
@using System.Globalization
@model SubtitlesManagementSystem.Web.Models.SubtitlesCatalogue.CatalogueItemsWithPaginationViewModel

<section class="upcoming-meetings meetings-page" id="meetings">
    <div class="container">
        @if (TempData["UserPromotionInfoMessage"] != null)
        {
            <div class="alert alert-success mb-3" role="alert">
                @TempData["UserPromotionInfoMessage"]
            </div>
        }

        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-lg-12 mb-5">
                        <form asp-action="Index" method="get">
                            <div class="form-actions no-color">
                                <p>
                                    <input type="text" name="SearchTerm" class="search-term-input"
                                           value="@ViewData["SubtitlesCatalogueSearchFilter"]" />
                                    <input type="submit" value="Search" class="btn btn-success rounded-pill" />
                                    <a asp-action="Index" class="btn btn-primary rounded-pill">Reset</a>
                                </p>
                            </div>
                        </form>
                    </div>
                    @if (!Model.AllSubtitlesForCatalogue.Any())
                    {
                        <h3>There are currently no subtitles</h3>
                    }
                    else
                    {
                        @foreach (var subtitles in Model.AllSubtitlesForCatalogue)
                        {
                            <div class="col-lg-4 templatemo-item-col all soon">
                                <div class="meeting-item">
                                    <div class="thumb">
                                        <div class="price">
                                            <span>@Html.DisplayFor(subtitlesModelItem => subtitles.RelatedFilmProduction.Duration) min.</span>
                                        </div>
                                        @if (subtitles.RelatedFilmProduction.ImageName != null)
                                        {
                                            <a asp-action="Details" asp-route-id="@subtitles.Id"><img src="~/images/film-productions/@subtitles.RelatedFilmProduction.ImageName" alt="" style="height: 300px;"></a>
                                        }
                                        else
                                        {
                                            <a asp-action="Details" asp-route-id="@subtitles.Id"><img src="~/images/film-productions/istockphoto-1147544807-612x612.jpg" alt="" style="height: 300px;"></a>
                                        }
                                    </div>
                                    <div class="down-content border border-dark">
                                        @if (subtitles.UploadedOn != null)
                                        {
                                            <div class="date">
                                                @{
                                                    var subtitlesUploadedOnAbbreviatedMonthName = CultureInfo.CurrentCulture.DateTimeFormat.GetAbbreviatedMonthName(subtitles.UploadedOn.Value.Month);
                                                }
                                                <h6>
                                                    @Html.DisplayFor(subtitlesModelItem => subtitlesUploadedOnAbbreviatedMonthName)
                                                    <span>@Html.DisplayFor(subtitlesModelItem => subtitles.UploadedOn.Value.Day)</span>
                                                </h6>
                                            </div>
                                        }
                                        <a asp-action="Details" asp-route-id="@subtitles.Id"><h4>@Html.DisplayFor(subtitlesModelItem => subtitles.Name)</h4></a>
                                        <p>Uploaded By: @Html.DisplayFor(subtitlesModelItem => subtitles.UploaderUserName)</p>
                                    </div>
                                </div>
                            </div>
                        }
                        <div class="col-12">
                            <div class="pagination" style="margin-bottom: 50px;">
                                <ul>
                                    <li>
                                        <a asp-action="Index"
                                           asp-route-pageNumber="@(Model.AllSubtitlesForCatalogue.PageIndex - 1)"
                                           asp-route-pageSize="@ViewData["CurrentPageSize"]"
                                           asp-route-currentFilter="@ViewData["SubtitlesCatalogueSearchFilter"]"
                                           class="btn @(!Model.AllSubtitlesForCatalogue.HasPreviousPage ? "border border-dark disabled" : "border border-dark")" style="line-height: 25px;">
                                            <i class="fa fa-angle-left"></i>
                                        </a>
                                    </li>
                                    @for (int pageIndex = 1; pageIndex <= @Model.AllSubtitlesForCatalogue.TotalPages; pageIndex++)
                                    {
                                        <li>
                                            <a style="@(Model.AllSubtitlesForCatalogue.PageIndex == pageIndex ? "color: white; background-color: #a12c2f;" : "")"
                                               asp-action="Index"
                                               asp-route-currentFilter="@ViewData["SubtitlesCatalogueSearchFilter"]"
                                               asp-route-pageSize="@ViewData["CurrentPageSize"]"
                                               asp-route-pageNumber="@pageIndex" style="line-height: 25px;" s>
                                                @pageIndex
                                            </a>
                                        </li>
                                    }
                                    <li>
                                        <a asp-action="Index"
                                           asp-route-pageNumber="btn @(Model.AllSubtitlesForCatalogue.PageIndex + 1)"
                                           asp-route-pageSize="@ViewData["CurrentPageSize"]"
                                           asp-route-currentFilter="@ViewData["SubtitlesCatalogueSearchFilter"]"
                                           class="btn @(!Model.AllSubtitlesForCatalogue.HasNextPage ? "border border-dark disabled" : "border border-dark")" style="line-height: 25px;">
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="col-lg-4">
                <div class="categories border border-dark">
                @if (!Model.LatestComments.Any())
                {
                    <h5>There are currently no comments</h5>
                }
                else
                {
                    <div class="mb-5">
                        <h5>Latest Comments</h5>
                        <ul class="list-group">
                            @foreach (var latestComment in Model.LatestComments)
                            {
                                <li class="list-group-item">
                                   @latestComment.UserName commented on
                                    <a class="link-primary" asp-action="Details" asp-route-id="@latestComment.SubtitlesId">
                                        @latestComment.SubtitlesName
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                }
            </div>
            <div class="categories border border-dark mt-3">
                @if (!Model.TopSubtitles.Any())
                {
                    <h5>No subtitles have been added to favourites yet</h5>
                }
                else
                {
                    <div>
                        <h5>Top Subtitles</h5>
                        <ul class="list-group mb-3">
                            @foreach (var topSubtitlesEntry in Model.TopSubtitles)
                            {
                                <li class="list-group-item">
                                    <a class="link-primary" asp-action="Details" asp-route-id="@topSubtitlesEntry.Id">
                                        @topSubtitlesEntry.Name
                                    </a>
                                    uploaded by @topSubtitlesEntry.UploaderUserName
                                </li>
                            }
                        </ul>
                    </div>
                }
            </div>
        </div>
    </div>
</section>